# Generated by Django 4.1.4 on 2023-01-12 10:08

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientPageBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_image', models.ImageField(upload_to='client_banner/images')),
                ('title', models.CharField(max_length=100)),
                ('how_it_work_title', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Our Client',
            },
        ),
        migrations.CreateModel(
            name='ClientsHowItWorks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(upload_to='home/customer_love')),
                ('text', models.CharField(max_length=250)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ourclient.clientpagebanner')),
            ],
            options={
                'verbose_name_plural': 'How It Works',
            },
        ),
        migrations.CreateModel(
            name='ClientPageSectionThree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('title_description', ckeditor.fields.RichTextField()),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ourclient.clientpagebanner')),
            ],
            options={
                'verbose_name_plural': 'Section 3',
            },
        ),
        migrations.CreateModel(
            name='ClientPageSectionOne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('title_description', ckeditor.fields.RichTextField()),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ourclient.clientpagebanner')),
            ],
            options={
                'verbose_name_plural': 'Section 1',
            },
        ),
        migrations.CreateModel(
            name='ClientPageSectionFour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('title_description', ckeditor.fields.RichTextField()),
                ('image', models.ImageField(upload_to='client-section-2/images')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ourclient.clientpagebanner')),
            ],
            options={
                'verbose_name_plural': 'Section 4',
            },
        ),
    ]
