# Generated by Django 4.1.4 on 2023-01-04 14:37

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactus',
            name='contact_us_title_gradient_text',
        ),
        migrations.RemoveField(
            model_name='contactus',
            name='contact_us_title_simple_text',
        ),
        migrations.AddField(
            model_name='contactus',
            name='contact_us_title',
            field=models.CharField(default=django.utils.timezone.now, max_length=255, verbose_name='Title'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ContactBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Banner Title')),
                ('banner', models.ImageField(upload_to='contact_banner/image')),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contact.contactus')),
            ],
            options={
                'verbose_name': 'Contact Banner',
                'verbose_name_plural': 'Contact Banner',
            },
        ),
    ]
