# Generated by Django 4.1.4 on 2023-01-12 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_remove_contactus_contact_us_title_gradient_text_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactus',
            name='contact_us_description',
        ),
    ]
