# Generated by Django 4.1.4 on 2023-01-04 15:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicespagebanner',
            name='banner_image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='services_banner/images'),
            preserve_default=False,
        ),
    ]
