# Generated by Django 4.1.4 on 2023-01-12 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_servicespagebanner_banner_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicesparagraph',
            name='image',
        ),
        migrations.CreateModel(
            name='HowItWorks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(upload_to='home/customer_love')),
                ('text', models.CharField(max_length=250)),
                ('services', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='services.servicespagebanner')),
            ],
            options={
                'verbose_name_plural': 'How It Works',
            },
        ),
    ]
