from .homepageslider_admin import HomePageSliderAdmin
from .homepagecontent_admin import HomePageContentAdmin
from .homepagefooter_admin import FooterAdmin
from .homepagehistory_admin import HomePageHistoryAdmin
from .homepagenewsletter_admin import HomePageNewsLetterAdmin

from .homepagevaluesandmission_admin import HomePageValueAndMissionsAdmin