# Generated by Django 4.1.4 on 2023-01-03 14:18

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='home/logo')),
                ('newsletter_title', models.CharField(max_length=100)),
                ('newsletter_description', models.CharField(max_length=255)),
                ('services_title_simple_text', models.CharField(max_length=255)),
                ('services_title_gradient_text', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Home Page ',
            },
        ),
        migrations.CreateModel(
            name='HomePageNewsLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('created_at', models.DateField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'NewsLetter',
            },
        ),
        migrations.CreateModel(
            name='HomePageValueAndMissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='home/valueandmission')),
                ('title', models.CharField(max_length=100)),
                ('description', ckeditor.fields.RichTextField()),
                ('home', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.homepagecontent')),
            ],
            options={
                'verbose_name_plural': 'Values And Missions',
            },
        ),
        migrations.CreateModel(
            name='HomePageSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=2000)),
                ('home', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.homepagecontent')),
            ],
            options={
                'verbose_name_plural': 'Home Page Slider',
            },
        ),
        migrations.CreateModel(
            name='HomePageServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='home/services')),
                ('title', models.CharField(max_length=100)),
                ('description', ckeditor.fields.RichTextField()),
                ('home', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.homepagecontent')),
            ],
            options={
                'verbose_name_plural': 'Services',
            },
        ),
        migrations.CreateModel(
            name='HomePageHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('simple_title', models.CharField(max_length=100)),
                ('gradient_title', models.CharField(max_length=100)),
                ('description', ckeditor.fields.RichTextField()),
                ('image', models.ImageField(upload_to='history/image')),
                ('home', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.homepagecontent')),
            ],
            options={
                'verbose_name_plural': 'History',
            },
        ),
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('footer_description', models.CharField(max_length=2000)),
                ('office_address', models.CharField(max_length=2000)),
                ('phone_no', models.CharField(max_length=1000)),
                ('email', models.EmailField(max_length=254)),
                ('home', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.homepagecontent')),
            ],
            options={
                'verbose_name_plural': 'Footer',
            },
        ),
    ]
