# Generated by Django 4.1.4 on 2023-01-04 14:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_homepagehistory_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='footer',
            name='footer_logo',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='home/logo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homepageslider',
            name='slider_image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='slider/image'),
            preserve_default=False,
        ),
    ]
