# Generated by Django 4.1.4 on 2023-01-11 11:08

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_footer_footer_logo_homepageslider_slider_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homepagevalueandmissions',
            options={'verbose_name_plural': 'Missions and Ideal Clients'},
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='how_it_work_title',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='homepageslider',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.CreateModel(
            name='HowItWorks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(upload_to='home/customer_love')),
                ('text', models.CharField(max_length=250)),
                ('home', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.homepagecontent')),
            ],
            options={
                'verbose_name_plural': 'How It Works',
            },
        ),
    ]
