# Generated by Django 4.1.4 on 2023-01-12 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_homepagevalueandmissions_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepagecontent',
            name='how_it_work_title',
        ),
        migrations.RemoveField(
            model_name='homepagecontent',
            name='services_title',
        ),
        migrations.DeleteModel(
            name='HowItWorks',
        ),
    ]
