# Generated by Django 4.1.4 on 2023-01-04 14:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companypage',
            name='about_banner',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='about_banner/images'),
            preserve_default=False,
        ),
    ]
