# Generated by Django 4.1.4 on 2023-01-12 10:08

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_companypage_about_banner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companypage',
            name='heading',
        ),
        migrations.RemoveField(
            model_name='companypage',
            name='heading_description',
        ),
        migrations.RemoveField(
            model_name='companypage',
            name='image',
        ),
        migrations.RemoveField(
            model_name='companypage',
            name='title',
        ),
        migrations.RemoveField(
            model_name='companypage',
            name='title_description',
        ),
        migrations.CreateModel(
            name='CompanySectionTwo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=100)),
                ('heading_description', ckeditor.fields.RichTextField()),
                ('image', models.ImageField(upload_to='about_section_1/images')),
                ('about', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.companypage')),
            ],
            options={
                'verbose_name_plural': 'About Section 2',
            },
        ),
        migrations.CreateModel(
            name='CompanySectionThree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('title_description', ckeditor.fields.RichTextField()),
                ('about', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.companypage')),
            ],
            options={
                'verbose_name_plural': 'About Section 3',
            },
        ),
        migrations.CreateModel(
            name='CompanySectionOne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('title_description', ckeditor.fields.RichTextField()),
                ('about', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.companypage')),
            ],
            options={
                'verbose_name_plural': 'About Section 1',
            },
        ),
        migrations.CreateModel(
            name='CompanySectionFour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('title_description', ckeditor.fields.RichTextField()),
                ('image', models.ImageField(upload_to='about_section_3/images')),
                ('about', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.companypage')),
            ],
            options={
                'verbose_name_plural': 'About Section 4',
            },
        ),
        migrations.CreateModel(
            name='CompanySectionFive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('title_description', ckeditor.fields.RichTextField()),
                ('about', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.companypage')),
            ],
            options={
                'verbose_name_plural': 'About Section 5',
            },
        ),
    ]
